stages:
  - build
  - deploy

.tag_only:
  only:
    refs:
      - tags

build:
  extends: .tag_only
  stage: build
  script:
    - build.bat --buildDir "${CI_COMMIT_TAG}"
  artifacts:
    name: "VRtist_${CI_COMMIT_TAG}"
    paths:
      - "Build/VRtist_${CI_COMMIT_TAG}"
  tags:
    - unity

deploy:
  extends: .tag_only
  stage: deploy
  script:
    - xcopy /y/s/e Build/VRtist_${CI_COMMIT_TAG} \\ubisoft.org\mtrstudio\World\UAS\Tech\VRTist\Releases\
  tags:
    - uas
