stages:
  - build
  - deploy

.tag_only:
  only:
    refs:
      - tags

build:
  extends: .tag_only
  stage: build
  script:
    - Get-Location
    - build.bat --buildDir "${CI_COMMIT_TAG}"
    - echo ${CI_COMMIT_TAG} > "Build\${CI_COMMIT_TAG}\version.txt"
  artifacts:
    name: "VRtist_${CI_COMMIT_TAG}"
    paths:
      - "Build/${CI_COMMIT_TAG}"
  tags:
    - unity

deploy:
  extends: .tag_only
  stage: deploy
  script:
    - xcopy /y/s/e Build\${CI_COMMIT_TAG} \\ubisoft.org\mtrstudio\World\UAS\Tech\VRTist\Releases\
  tags:
    - uas
