stages:
  - build
  - deploy

.tag_only:
  only:
    refs:
      - tags

build:
  extends: .tag_only
  stage: build
  script:
    - echo %UNITY_EXE%
    - .\.gitlab\build.bat "${UNITY_EXE}" --buildDir "${CI_COMMIT_TAG}"
    - echo ${CI_COMMIT_TAG} > "Build\${CI_COMMIT_TAG}\version.txt"
  artifacts:
    name: "VRtist_${CI_COMMIT_TAG}"
    paths:
      - "Build/${CI_COMMIT_TAG}"
  tags:
    - unity

deploy:
  extends: .tag_only
  stage: deploy
  script:
    - xcopy /y/s/e/i Build\${CI_COMMIT_TAG} ${UAS_DEPLOY_FOLDER}\${CI_COMMIT_TAG}
    - python create_github_release --tag ${CI_COMMIT_TAG} --name ${CI_COMMIT_TAG} --zip
  tags:
    - uas
